#' AI guidance for blueprint step selection
#'
#' Internal usage prompts keyed by exported step function name. These prompts are
#' included in the system prompt used by [inquire_blueprint()], but are not
#' exposed in user-facing function documentation.
#'
#' @returns A named character vector.
#' @noRd
.step_ai_prompts <- function() {
  c(
    step_adjust_protein = "Include this step only if the user explicitly asks for protein adjustment. If protein adjustment is needed and the `pro_expr_path` is not provided, ask for it and explain how to prepare the file: - CSV/TSV: first column is protein accessions; remaining columns are sample names. - RDS: a matrix/data.frame with row names as protein accessions and columns as sample names. You MUST provide a detailed explanation of how to prepare the file. Without the file, the step is invalid.",
    step_correlation = "Include this step to explore relationships between variables or samples. Be careful to use when sample size or variable number is large (> 50). Before using this step for large data, ask the user if they want to proceed.",
    step_cox = "Include this step when users want to identify variables associated with survival outcomes. This step requires survival data (time and event columns) in the sample information. Always ask for the column names for survival data, unless explicitly provided.",
    step_dea_anova = "Include this step only if the user explicitly asks for ANOVA.",
    step_dea_kruskal = "Include this step only if the user explicitly asks for Kruskal-Wallis test.",
    step_dea_limma = "Use this step to perform DEA by default, unless the user asks for other methods.",
    step_dea_ttest = "Include this step only if the user explicitly asks for t-test. If the experiment has more than 2 groups but the user wants a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before this step.",
    step_dea_wilcox = "Include this step only if the user explicitly asks for Wilcoxon test. If the experiment has more than 2 groups but the user wants a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before this step.",
    step_derive_traits = "Include this step by default if the experiment has glycan structures. After this step, it should be followed by the DEA and visualization steps.",
    step_heatmap = "Include this step if needed. It is recommended to use this step on significant results (e.g. `on = \"sig_exp\"`) if available.",
    step_ident_overview = "Always include this step by default unless the user explicitly excludes it. Use it as the first step in the blueprint.",
    step_infer_structure = "Include this step when the user requests structure-aware analysis but the experiment has glycan compositions and no glycan structures. This step should be placed before `step_derive_traits()`, `step_quantify_dynamic_motifs()`, or `step_quantify_branch_motifs()`. Mention that variables without inferred structures are removed. Always ask for species restriction to improve inference accuracy, but allow users to skip it if they want.",
    step_logo = "Include this step if the user explicitly asks for logo plot. If used, ask user if a FASTA file is provided. Tell the user that if not, protein sequences will be fetched from UniProt automatically.",
    step_oplsda = "Include this step when users explicitly ask for OPLS-DA. This step only works with binary classification (exactly 2 groups). If multiple groups are found, ask if `step_subset_groups()` should be run first.",
    step_pca = "Include this step if needed.",
    step_plot_qc = "By default, include this step ONLY after `step_preprocess()`. You MUST provide the when parameter to specify when the QC is being run.",
    step_plsda = "Include this step when users explicitly ask for PLS-DA.",
    step_preprocess = "Always include this step by default unless the user explicitly excludes it or tell you she/he has already performed preprocessing. Ask for the column name for batch information if not provided. Ask for QC samples in the experiment if not provided. If so, ask the group name of the QC samples. Explain to the user that if it is \"QC\" for example, the samples with \"QC\" in the `group_col` column will be considered as QC samples. And these QC samples will be used for choosing the best normalization and imputation methods. Also mention that QC samples will be excluded after preprocessing. If the user intends to perform biomarker related analysis, set `remove_preset` to \"biomarker\". Use default values for other arguments unless the user explicitly specifies otherwise.",
    step_quantify_branch_motifs = "Include this step if motif analysis is needed specifically for N-glycans. This step should be followed by DEA and visualization steps.",
    step_quantify_dynamic_motifs = "Include this step if motif analysis is needed for non-N-glycans or when comprehensive motif extraction is desired. This step should be followed by DEA and visualization steps.",
    step_roc = "Include this step if the user explicitly asks for ROC analysis, or if he/she mentions \"biomarker(s)\" in the prompt. If the experiment has more than 2 groups but the user wants a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before this step.",
    step_sig_boxplot = "Include this step after DEA steps to visualize the significant variables. This step is particularly useful for understanding the expression patterns of the most differentially expressed features across groups.",
    step_sig_enrich_do = "Include this step if user asks for it. Leave `universe` to \"all\" (by default) unless the user explicitly mentions that the background should be the detected variables in `exp`. If the experiment has more than 2 groups but the user wants enrichment for a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before DEA and enrichment steps.",
    step_sig_enrich_go = "Include this step by default if DEA is performed on glycoproteomics data. Leave `universe` to \"all\" (by default) unless the user explicitly mentions that the background should be the detected variables in `exp`. If the experiment has more than 2 groups but the user wants enrichment for a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before DEA and enrichment steps.",
    step_sig_enrich_kegg = "Include this step by default if DEA is performed on glycoproteomics data. Leave `universe` to \"all\" (by default) unless the user explicitly mentions that the background should be the detected variables in `exp`. If the experiment has more than 2 groups but the user wants enrichment for a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before DEA and enrichment steps.",
    step_sig_enrich_ncg = "Include this step if user asks for it. Leave `universe` to \"all\" (by default) unless the user explicitly mentions that the background should be the detected variables in `exp`. If the experiment has more than 2 groups but the user wants enrichment for a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before DEA and enrichment steps.",
    step_sig_enrich_reactome = "Include this step if user asks for it. Leave `universe` to \"all\" (by default) unless the user explicitly mentions that the background should be the detected variables in `exp`. If the experiment has more than 2 groups but the user wants enrichment for a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before DEA and enrichment steps.",
    step_sig_enrich_wp = "Include this step if user asks for it. Leave `universe` to \"all\" (by default) unless the user explicitly mentions that the background should be the detected variables in `exp`. If the experiment has more than 2 groups but the user wants enrichment for a specific two-group comparison, ask which two groups to compare and include `step_subset_groups(groups = c(\"A\", \"B\"))` before DEA and enrichment steps.",
    step_subset_groups = "Use this step when the experiment has more than 2 groups but the user wants a specific two-group comparison. Ask the user which two groups to compare, and place this step before DEA and enrichment steps. Use the order of the user-provided groups to set factor levels.",
    step_tsne = "Include this step only when the user explicitly asks for t-SNE.",
    step_umap = "Include this step only when the user explicitly asks for UMAP.",
    step_volcano = "Always include this step by default if DEA is performed, and the DEA method is not ANOVA or Kruskal-Wallis."
  )
}
