#' Step: GO Enrichment Analysis on Differentially Expressed Variables
#'
#' @description
#' Perform GO enrichment analysis on differentially expressed variables using `glyfun::enrich_ora_go()`.
#'
#' This step requires `dea_res` (differential analysis result from DEA).
#' Run one of [step_dea_limma()], [step_dea_ttest()], or [step_dea_wilcox()] before this step.
#' Only execute for glycoproteomics experiments with exactly 2 groups.
#' If used for glycomics experiments, the step will be skipped.
#' Use all genes in OrgDb as the background.
#'
#' @details
#' Data required:
#' - `exp`: The experiment to perform GO enrichment analysis for
#' - `dea_res`: The result from DEA, generated by `step_dea_xxx()`.
#'
#' Tables generated:
#' - `go_enrich`: A table containing the GO enrichment results.
#'
#' @section AI Prompt:
#' *This section is for AI in [inquire_blueprint()] only.*
#'
#' - Include this step if needed.
#' - Leave `universe` to "all" (by default) unless the user explicitly mentions that
#'   the background should be the detected variables in `exp`.
#' - If the experiment has more than 2 groups but the user wants enrichment for a
#'   specific two-group comparison, ask which two groups to compare and include
#'   `step_subset_groups(groups = c("A", "B"))` before DEA and enrichment steps.
#'
#' @param universe The universe (background) to use for enrichment analysis.
#'   One of "all" (all genes in OrgDb), "detected" (detected variables in `exp`).
#' @param plot_type Plot type for enrichment results ("dotplot", "barplot", etc.).
#' @param plot_width Width of the plot in inches. Default is 7.
#' @param plot_height Height of the plot in inches. Default is 7.
#' @param ... Additional arguments passed to [glyfun::enrich_ora_go()].
#'
#' @return A `glysmith_step` object.
#' @examples
#' step_sig_enrich_go()
#' step_sig_enrich_go(plot_type = "barplot")
#' @seealso [glyfun::enrich_ora_go()]
#' @export
step_sig_enrich_go <- function(
  universe = "all",
  plot_type = "dotplot",
  plot_width = 7,
  plot_height = 7,
  ...
) {
  signature <- rlang::expr_deparse(match.call())
  step_sig_enrich(
    "go",
    universe = universe,
    plot_type = plot_type,
    plot_width = plot_width,
    plot_height = plot_height,
    signature = signature,
    ...
  )
}

#' Step: KEGG Enrichment Analysis on Differentially Expressed Variables
#'
#' @description
#' Perform KEGG enrichment analysis on differentially expressed variables using `glyfun::enrich_ora_kegg()`.
#'
#' This step requires `dea_res` (differential analysis result from DEA).
#' Run one of [step_dea_limma()], [step_dea_ttest()], or [step_dea_wilcox()] before this step.
#' Only execute for glycoproteomics experiments with exactly 2 groups.
#' If used for glycomics experiments, the step will be skipped.
#' Use all genes in OrgDb as the background.
#'
#' @details
#' Data required:
#' - `exp`: The experiment to perform KEGG enrichment analysis for
#' - `dea_res`: The result from DEA, generated by `step_dea_xxx()`.
#'
#' Tables generated:
#' - `kegg_enrich`: A table containing the KEGG enrichment results.
#'
#' @section AI Prompt:
#' *This section is for AI in [inquire_blueprint()] only.*
#'
#' - Include this step if needed.
#' - Leave `universe` to "all" (by default) unless the user explicitly mentions that
#'   the background should be the detected variables in `exp`.
#' - If the experiment has more than 2 groups but the user wants enrichment for a
#'   specific two-group comparison, ask which two groups to compare and include
#'   `step_subset_groups(groups = c("A", "B"))` before DEA and enrichment steps.
#'
#' @param universe The universe (background) to use for enrichment analysis.
#'   One of "all" (all genes in OrgDb), "detected" (detected variables in `exp`).
#' @param plot_type Plot type for enrichment results ("dotplot", "barplot", etc.).
#' @param plot_width Width of the plot in inches. Default is 7.
#' @param plot_height Height of the plot in inches. Default is 7.
#' @param ... Additional arguments passed to [glyfun::enrich_ora_kegg()].
#'
#' @return A `glysmith_step` object.
#' @examples
#' step_sig_enrich_kegg()
#' step_sig_enrich_kegg(plot_type = "barplot")
#' @seealso [glyfun::enrich_ora_kegg()]
#' @export
step_sig_enrich_kegg <- function(
  universe = "all",
  plot_type = "dotplot",
  plot_width = 7,
  plot_height = 7,
  ...
) {
  signature <- rlang::expr_deparse(match.call())
  step_sig_enrich(
    "kegg",
    universe = universe,
    plot_type = plot_type,
    plot_width = plot_width,
    plot_height = plot_height,
    retry = 2L,
    signature = signature,
    ...
  )
}

#' Step: Reactome Enrichment Analysis on Differentially Expressed Variables
#'
#' @description
#' Perform Reactome enrichment analysis on differentially expressed variables using `glyfun::enrich_ora_reactome()`.
#'
#' This step requires `dea_res` (differential analysis result from DEA).
#' Run one of [step_dea_limma()], [step_dea_ttest()], or [step_dea_wilcox()] before this step.
#' Only execute for glycoproteomics experiments with exactly 2 groups.
#' If used for glycomics experiments, the step will be skipped.
#' Use all genes in OrgDb as the background.
#'
#' @details
#' Data required:
#' - `exp`: The experiment to perform Reactome enrichment analysis for
#' - `dea_res`: The result from DEA, generated by `step_dea_xxx()`.
#'
#' Tables generated:
#' - `reactome_enrich`: A table containing the Reactome enrichment results.
#'
#' @section AI Prompt:
#' *This section is for AI in [inquire_blueprint()] only.*
#'
#' - Include this step if needed.
#' - Leave `universe` to "all" (by default) unless the user explicitly mentions that
#'   the background should be the detected variables in `exp`.
#' - If the experiment has more than 2 groups but the user wants enrichment for a
#'   specific two-group comparison, ask which two groups to compare and include
#'   `step_subset_groups(groups = c("A", "B"))` before DEA and enrichment steps.
#'
#' @param universe The universe (background) to use for enrichment analysis.
#'   One of "all" (all genes in OrgDb), "detected" (detected variables in `exp`).
#' @param plot_type Plot type for enrichment results ("dotplot", "barplot", etc.).
#' @param plot_width Width of the plot in inches. Default is 7.
#' @param plot_height Height of the plot in inches. Default is 7.
#' @param ... Additional arguments passed to [glyfun::enrich_ora_reactome()].
#'
#' @return A `glysmith_step` object.
#' @examples
#' step_sig_enrich_reactome()
#' step_sig_enrich_reactome(plot_type = "barplot")
#' @seealso [glyfun::enrich_ora_reactome()]
#' @export
step_sig_enrich_reactome <- function(
  universe = "all",
  plot_type = "dotplot",
  plot_width = 7,
  plot_height = 7,
  ...
) {
  signature <- rlang::expr_deparse(match.call())
  step_sig_enrich(
    "reactome",
    universe = universe,
    plot_type = plot_type,
    plot_width = plot_width,
    plot_height = plot_height,
    retry = 2L,
    signature = signature,
    ...
  )
}

#' Step: Enrichment Analysis on Differentially Expressed Variables
#'
#' @description
#' Run functional enrichment analysis on differentially expressed variables using one of:
#' - `glyfun::enrich_ora_go()`
#' - `glyfun::enrich_ora_kegg()`
#' - `glyfun::enrich_ora_reactome()`
#'
#' This step requires one of the DEA steps to be run.
#' Only execute for glycoproteomics experiments with exactly 2 groups.
#' Use all genes in OrgDb as the background.
#'
#' @param kind Enrichment type: `"go"`, `"kegg"`, or `"reactome"`.
#' @param universe The universe (background) to use for enrichment analysis.
#'   One of "all" (all genes in OrgDb), "detected" (detected variables in `exp`).
#' @param plot_width Width of the plot in inches.
#' @param plot_height Height of the plot in inches.
#' @param retry Number of retries if the step errors.
#' @noRd
step_sig_enrich <- function(
  kind = c("go", "kegg", "reactome"),
  universe = c("all", "detected"),
  plot_type = "dotplot",
  plot_width = 7,
  plot_height = 7,
  retry = 0L,
  signature = NULL,
  ...
) {
  kind <- rlang::arg_match(kind)
  universe <- rlang::arg_match(universe)
  label <- paste0(toupper(kind), " enrichment analysis")
  step_id <- paste0("sig_enrich_", kind)
  enrich_args <- rlang::list2(...)

  step(
    id = step_id,
    label = label,
    condition = function(ctx) {
      check1 <- glyexp::get_exp_type(ctx_get_data(ctx, "exp")) ==
        "glycoproteomics"
      reason1 <- "input is not a glycoproteomics experiment"
      check2 <- length(unique(ctx_get_data(ctx, "exp")$sample_info$group)) == 2
      reason2 <- "input has more than 2 groups"
      if (check1 && check2) {
        list(check = TRUE, reason = NULL)
      } else if (check1 && !check2) {
        list(check = FALSE, reason = reason2)
      } else if (!check1 && check2) {
        list(check = FALSE, reason = reason1)
      } else {
        list(check = FALSE, reason = paste0(reason1, " and ", reason2))
      }
    },
    run = function(ctx) {
      dea_res <- ctx_get_data(ctx, "dea_res")
      call_args <- enrich_args
      if (universe == "detected") {
        # Force universe to be the detected proteins, overriding any dots.
        call_args$universe <- glyfun::detected_universe(ctx_get_data(ctx, "exp"))
      }
      enrich_res <- switch(
        kind,
        go = rlang::exec(glyfun::enrich_ora_go, dea_res, !!!call_args),
        kegg = rlang::exec(glyfun::enrich_ora_kegg, dea_res, !!!call_args),
        reactome = rlang::exec(
          glyfun::enrich_ora_reactome,
          dea_res,
          !!!call_args
        )
      )
      ctx <- ctx_add_table(
        ctx,
        kind,
        .tidy_glyfun_enrich_result(enrich_res),
        paste0(toupper(kind), " enrichment analysis results.")
      )
      p <- .plot_glyfun_enrich(enrich_res, type = plot_type)
      ctx_add_plot(
        ctx,
        kind,
        p,
        paste0(toupper(kind), " enrichment analysis plot."),
        width = plot_width,
        height = plot_height
      )
    },
    report = function(x) {
      tbl <- x$tables[[kind]]
      n_sig <- sum(tbl$p_adj < 0.05)
      msg <- paste0(
        "Enrichment analysis was performed on differentially expressed variables."
      )
      if (n_sig > 0) {
        msg <- paste0(
          msg,
          " Number of significant items (adjusted p < 0.05): ",
          n_sig,
          ".\n\n"
        )
        all_sig_terms <- tbl$description[tbl$p_adj < 0.05]
        all_sig_terms_part <- paste(all_sig_terms, collapse = ", ")
        msg <- paste0(
          msg,
          glue::glue(
            "<AI>Summarize these terms in 1 sentence: {all_sig_terms_part}</AI>"
          )
        )
        msg <- paste0(
          msg,
          "Top terms: \n\n",
          paste("- ", tbl$description[1:min(5, n_sig)], collapse = "\n"),
          "\n"
        )
      } else {
        msg <- paste0(msg, " No significant items (adjusted p < 0.05).\n")
      }
      msg
    },
    require = c("exp", "dea_res"),
    retry = retry,
    signature = signature
  )
}

#' Tidy a glyfun enrichment result for GlySmith tables
#'
#' @param enrich_res A clusterProfiler enrichment result returned by `glyfun`, or
#'   `NULL` when no term is enriched.
#'
#' @returns A tibble with GlySmith-compatible column names.
#' @noRd
.tidy_glyfun_enrich_result <- function(enrich_res) {
  if (is.null(enrich_res)) {
    return(tibble::tibble(description = character(), p_adj = numeric()))
  }

  tbl <- tibble::as_tibble(enrich_res)
  col_map <- c(
    Description = "description",
    pvalue = "p_val",
    `p.adjust` = "p_adj",
    qvalue = "q_val",
    geneID = "gene_id"
  )
  matched <- intersect(names(col_map), names(tbl))
  names(tbl)[match(matched, names(tbl))] <- unname(col_map[matched])
  tbl
}

#' Plot a glyfun enrichment result
#'
#' @param enrich_res A clusterProfiler enrichment result returned by `glyfun`, or
#'   `NULL` when no term is enriched.
#' @param type Plot type. One of "dotplot", "barplot", or "network".
#' @param ... Additional arguments passed to the enrichplot function.
#'
#' @returns A ggplot object.
#' @noRd
.plot_glyfun_enrich <- function(enrich_res, type = "dotplot", ...) {
  if (is.null(enrich_res)) {
    return(ggplot2::ggplot())
  }

  rlang::check_installed("enrichplot")
  checkmate::assert_choice(type, c("dotplot", "barplot", "network"))
  switch(
    type,
    dotplot = enrichplot::dotplot(enrich_res, ...),
    barplot = barplot(enrich_res, ...),
    network = enrichplot::emapplot(enrichplot::pairwise_termsim(enrich_res), ...)
  )
}
